# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jufk < Formula
  desc "A CLI tool for JUFK"
  homepage "https://github.com/adjorno/jufk"
  version "0.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/adjorno/jufk/releases/download/v0.3.7/jufk-macos-arm64"
      sha256 "01af7cd658dcb3974d5b0c070cd7a6a14b8fc6fe64bd7f9885fdb24c3778a56c"
    end
    if Hardware::CPU.intel?
      url "https://github.com/adjorno/jufk/releases/download/v0.3.7/jufk-macos-x64"
      sha256 "1944f003fdac8f9f7deeeb5813b7a011a1d971166895a15932ecbaa452f851e5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/adjorno/jufk/releases/download/v0.3.7/jufk-linux-x64"
      sha256 "6b22f46bf52a3ce8063b22f9df0d9c17a1983007dae8a588f306995d5522d663"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        # FIX: Look for the original filename and install/rename it to "jufk"
        bin.install "jufk-macos-arm64" => "jufk"
      else
        bin.install "jufk-macos-x64" => "jufk"
      end
    elsif OS.linux?
      if Hardware::CPU.intel?
        bin.install "jufk-linux-x64" => "jufk"
      end
    end
  end
end
